version: A58_2023_02_27_0_0_1
md5: S58_ss_656546531

AHEAD_CTRL_POINT_NUM: 1
WIDTH_HALF: 0.9435
MIDDLE_TO_REAR: 0

MIDDLE_TO_REAR_FREESPACE: 1.349
AXIS_DISTANCE: 2.730
FRONT_USS_TO_FRONT_AXLE_DIST: 0.956
SENSORS_LONGITUDINAL_DIST: 3.28
HALF_VEHICLE_WIDTH: 0.9435

WHEEL_SPEED_PULSE_METERS_PER_PULSE: 0.0269
FL_WHEEL_SPEED_PULSE_METERS_PER_PULSE: 0.0269
FR_WHEEL_SPEED_PULSE_METERS_PER_PULSE: 0.0269
RL_WHEEL_SPEED_PULSE_METERS_PER_PULSE: 0.0269
RR_WHEEL_SPEED_PULSE_METERS_PER_PULSE: 0.0269

FRONT_WHEEL_SPAN: 1.617
REAR_WHEEL_SPAN: 1.610

VEHICLE_LEN: 4.650
VEHICLE_WID: 1.887
FRONT_EDGE2CENTER: 3.674
REAR_EDGE2CENTER: 0.976
SIDE_EDGE2CENTER: 0.9435
WHEEL_BASE: 2.730

CHAMFER_LENGTH: 0.4
FRONT_CHAMFER_L1: 0.0
FRONT_CHAMFER_L2: 0.0
REAR_CHAMFER_L1: 0.2
REAR_CHAMFER_L2: 0.2
CHAMFER_ANGLE: 45   #45*PI/180

REAR_VIEW_LENGTH: 0.2
REAR_VIEW_WIDTH: 0.25
REAR_VIEW_2_FRONT_AXLE: 2.16

#超声安装参数
middle_to_rear_freespace: 3.259
SIDE_LUR_CENTERY: 0.943
SIDE_LURR_CENTERX: 0.569
FURTHEST_SIDE_DISTANCE: 999

LeftCameraX: 2.0      #(REAR_VIEW_2_FRONT_AXLE - 0.16f)
LeftCameraY: 0.9935   #(VEHICLE_WID * 0.5 + 0.05)
RightCameraX: 2.0     #(LeftCameraX)
RightCameraY: -0.9935 #(-LeftCameraY)
FrontCameraX: 3.674   #(FRONT_EDGE2CENTER)
FrontCameraY: 0.0
RearCameraX: -0.976   #(-REAR_EDGE2CENTER)
RearCameraY: 0.0

SENSOR1_X: 3.564
SENSOR1_Y: 0.667
SENSOR1_ANGLE: 42     #(42 * PI / 180)
SENSOR2_X: 3.631
SENSOR2_Y: 0.345
SENSOR2_ANGLE: 7      #(7 * PI / 180)
SENSOR3_X:  3.631     #( SENSOR2_X )
SENSOR3_Y: -0.345     #(-SENSOR2_Y )
SENSOR3_ANGLE: -7     #(-SENSOR2_ANGLE )
SENSOR4_X: 3.564      #( SENSOR1_X )
SENSOR4_Y: -0.667     #(-SENSOR1_Y )
SENSOR4_ANGLE: -42    #(-SENSOR1_ANGLE )

SENSOR5_X: -0.902
SENSOR5_Y: 0.603
SENSOR5_ANGLE: 149    #(149 * PI / 180)
SENSOR6_X: -0.965
SENSOR6_Y: 0.249
SENSOR6_ANGLE: 173    #(173 * PI / 180)
SENSOR7_X: -0.965     #(SENSOR6_X )
SENSOR7_Y: -0.249     #(-SENSOR6_Y )
SENSOR7_ANGLE: -173   #(-SENSOR6_ANGLE )
SENSOR8_X: -0.902     #(SENSOR5_X )
SENSOR8_Y: -0.603     #(-SENSOR5_Y )
SENSOR8_ANGLE: -149   #( -SENSOR5_ANGLE )

SENSOR9_X: 3.259      #( SIDE_LURF_CENTER_X )
SENSOR9_Y: 0.9435     #( SIDE_EDGE2CENTER )
SENSOR9_ANGLE: 82     #(82 * PI / 180)
SENSOR10_X: 3.259     #( SENSOR9_X )
SENSOR10_Y: -0.9435   #(-SENSOR9_Y )
SENSOR10_ANGLE: -82   #(-SENSOR9_ANGLE )
SENSOR11_X: -0.569    #(-SIDE_LURR_CENTERX)
SENSOR11_Y: 0.9435    #( SIDE_EDGE2CENTER)
SENSOR11_ANGLE: 92    #(92 * PI / 180)// *pi/3 rad, 120 degree
COS_SENSOR11_DIS_ANGEL: 1.0
SENSOR12_X: -0.569    #(SENSOR11_X)
SENSOR12_Y: 0.9435    #(-SENSOR11_Y)
SENSOR12_ANGLE: -92   #(-SENSOR11_ANGLE)
COS_SENSOR12_DIS_ANGEL: 1.0

USS_K: 58
USS_K2: 7.752
SPEED_K: 1
PLUS_COUNT: 4096

#规划参数
MAX_STEERING_ANGLE: 456
MAX_STEERING_ANGLE_SPEED: 400                       #最大方向盘角速度
MAX_FRONT_AXLE_ANGLE: 0.6
#环视参数
CAMERA_2_MID: 0.58

#速度默认
VERY_DANGOUS_VELOCITY: 0.2
DANGOUS_VELOCITY: 0.3

#转向角误差
STEERING_WHEEL_ANGLE_ERROR: 10         #目标方向盘转角和实际方向盘转角最大允许差值

ADDIDEGREE: 0

#USS state
PROXIMITY: 16
NORMAL: 0    

GEAR_P: 1
GEAR_R: 2
GEAR_N: 3
GEAR_D: 4

EPSSteeringAngleRatiosRows: 11
EPSSteeringAngleRatiosClos: 5
EPSSteeringAngleRatios: 
    EPSSteeringAngleRatio_0: [170, 0.182713, 0.186183, 0.193731, 0.195271]
    EPSSteeringAngleRatio_1: [200, 0.213624, 0.210972, 0.225991, 0.225291]
    EPSSteeringAngleRatio_2: [230, 0.253340, 0.246417, 0.264447, 0.257712]
    EPSSteeringAngleRatio_3: [260, 0.281727, 0.283221, 0.295076, 0.292958]
    EPSSteeringAngleRatio_4: [290, 0.316585, 0.312152, 0.329033, 0.325144]
    EPSSteeringAngleRatio_5: [320, 0.353413, 0.348024, 0.334337, 0.362713]
    EPSSteeringAngleRatio_6: [350, 0.368205, 0.380656, 0.402151, 0.392548]
    EPSSteeringAngleRatio_7: [380, 0.423274, 0.415827, 0.438791, 0.427377]
    EPSSteeringAngleRatio_8: [410, 0.466571, 0.456298, 0.476865, 0.467039]
    EPSSteeringAngleRatio_9: [440, 0.504171, 0.483403, 0.517839, 0.498223]
    EPSSteeringAngleRatio_10: [470, 0.527227, 0.513124, 0.541730, 0.524689]


SteeringAngleMinDisLsitNum: 3     #暂不可修改
SteeringAngleMinDisLsitClos: 25   #暂不可修改
SteeringAngleMinDiss: 
    SteeringAngleMinDis_0: [0,35, 45, 45, 35,     -1, -1, -1, -1,     -1, -1, -1, -1,-1, -1, -1, -1,     30, 30, 30, 30,     -1, -1, -1, -1]
    SteeringAngleMinDis_1: [250,45, 45, 45, 45,     -1, -1, -1, -1,     35, -1, -1, -1,-1, -1, -1, -1,     35, 30, 30, 35,    -1, 25, 30, 30]
    SteeringAngleMinDis_2: [400,45, 45, 45, 45,     -1, -1, -1, -1,     35, -1, -1, -1,  -1, -1, -1, -1,    35, 35, 35, 35,     -1, 25, 30, 30]